apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: test
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: test
  labels:
    app: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql-root-password
        - name: PMA_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql-username
        - name: PMA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql-password
        - name: PMA_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mysql-database
        ports:
        - containerPort: 80
          name: phpmyadmin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"